name: validator
description: A Dart/Flutter package for validating input strings.
version: 1.0.0
repository: https://github.com/odunboye/validator

environment:
  sdk: ">=3.1.5 <4.0.0"

# Add regular dependencies here.
dependencies:
  # path: ^1.8.0
  intl: ^0.18.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.25.0
